### ISSUE TITLE
Option to add images

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-beaty-biodiversity-museum#102]
In case you haven't noticed, we have recently added the option to add images to grscicoll. I added an example in UAT
https://beaty-biodiversity-museum.hp.gbif-uat.org/collection/b44fcb7f-1227-4fa3-8ed2-de27aabb06e0

You already have the images I notice

**Comment by mpitblado** [comment]
Thanks for the ping! It looks like there are several UI updates on the way, so I'll keep my eyes out and then configure as appropriate when released!
