### ISSUE TITLE
Configure data scope for new collection view

### ISSUE THREAD

**Issue by mpitblado** [gbif/hp-beaty-biodiversity-museum#2]
I have updated the site to take advantage of the new collection view as presented at the last meeting. Similarly to how specimen/search is scoped to a particular set of datasets via 
```javascript
rootPredicate: {
  "type": "in",
  "key": "datasetKey",
  "values": [
    '4edd9396-59df-4b01-9e29-dc21a59f9963',
    '07fd0d79-4883-435f-bba1-58fef110cd13',
    '90302970-1bc6-4865-be76-9aef1dd707f9',
    '9c45867f-f77d-42f3-9751-ae16bb7c9bc8',
    '628abbe5-dc8d-41e9-a0c7-f05efe282649',
    'ca1bcd7e-7387-42f9-81ba-1470db55e3e8',
    '3ad882bb-cd21-4201-8b83-3684bfc6d830',
    'ba0c046d-52bb-4262-a495-652988c9f3f7',
    'df9c8b86-9d36-4e29-91b3-4274dff053e5'
  ]
},
```
I am wondering how I would go about scoping collection/search to only include a particular set of collections?

**Comment by MortenHofft** [comment]
It is now filtered by institution, you had simple inserted the collection config under the occurrences. It works now.
https://beaty-biodiversity-museum.hp.gbif-staging.org/collection/search

And we can remove the irrelevant filters as well.
But given that there are so few collections (not hundreds), then I would suggest to removed the collection search and replaced it by a list similar to the [100 treasures](https://beaty-biodiversity-museum.hp.gbif-staging.org/100-treasures) or another layout, but managed manually in code. It looks a bit silly with filters and a table with 3 entries. Obviously that is just my opinion

**Comment by MortenHofft** [comment]
@mpitblado it feels a bit sad to replace your nice collection page with the more generic GrSciColl one

https://beaty-biodiversity-museum.hp.gbif-staging.org/collections/cowan-tetrapod-collection
https://grscicoll.hp.gbif-staging.org/collection/3b2ad644-b3e4-4ac9-a57f-23be3f86ed0e

Adding some more metadata would help of course, but even then I suspect it won't look as nice. Tricky, I'm not sure what I can do. Ideas are welcome

**Comment by mpitblado** [comment]
Thanks @MortenHofft, ah that makes sense that it would just be under a collection heading in the config instead of occurrence. I'm glad you liked the collection pages! I am going to be sending the staging link around the museum for feedback next week, and will ask which one people prefer!

For now, I have updated the config to include the UBC institution with commit 0560249, as this will then have data for people to see next week. @ManonGros I met with the director today concerning the GrSciColl and will change the institution scope back to Beaty Biodiversity Museum once we have all of our collections under one roof!
