### ISSUE TITLE
Change base branch name from master to main

### ISSUE THREAD

**Issue by mpitblado** [gbif/hp-beaty-biodiversity-museum#33]
Both GitLab and GitHub have changed the default base branch name from master to main due to the historical connotations with using the master/slave vocabulary for repositories. 

[GitHub blog post on the issue](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)

[GitLab blog post on the issue](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/)

@MortenHofft If this change was made for this repository, would it have any consequences for the pipeline?

**Comment by MortenHofft** [comment]
It would break the deployment yes. But it might be as simple as changing one line in the config (it is also running a script that I do not have easy access to, so I'm not sure about that part). We can try it and see what happens?

**Comment by mpitblado** [comment]
Sure, seems like a good time to test it now rather than when prod is up. I'll make the change now and can revert if it doesn't work.

**Comment by mpitblado** [comment]
Looks like everything went fine, closing!
