### ISSUE TITLE
Fix navigation menu being covered by map menu options

### ISSUE THREAD

**Issue by mpitblado** [gbif/hp-beaty-biodiversity-museum#51]
Clicking on the navigation menu while in the map view leads to the navigation menu being covered up by the map menu (so the user cannot access the Specimens tab). This is likely a quick z-index fix.

![image](https://github.com/gbif/hp-beaty-biodiversity-museum/assets/116753126/72a13f1e-cc5b-4658-ab14-6a158f04cd4f)

**Comment by MortenHofft** [comment]
This could be changed 3 places. in the react widgets, the theme or in your site.
It made best sense to do it in the widgets i found.

**Comment by MortenHofft** [comment]
Ahh . i only just now realise that it is because we did custom styling of your menu dropdown. Anyway, above should fix it either way.

**Comment by mpitblado** [comment]
Can confirm now fixed due to the push to the widget! Thanks
