### ISSUE TITLE
W3 HTML Validator bugs

### ISSUE THREAD

**Issue by mpitblado** [gbif/hp-beaty-biodiversity-museum#92]
A list of issues to fix can be displayed by going to: https://validator.w3.org/nu/?doc=https%3A%2F%2Fcollections.beatymuseum.ubc.ca%2F (validator plus the query that points to collections.beatymuseum.ubc.ca)

**Comment by MortenHofft** [comment]
I haven't look at the report carefully, but be sceptical of anything coming from w3 - they are infamous for their low quality and plain wrong advice.

Just briefly scanning many of the errors has to do with trailing slashed on links. Which According to mdn and code checkers are the correct syntax. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link

That isn't to say that there couldn't be actual errors and useful stuff in there, but I would double check everything

**Comment by mpitblado** [comment]
Interesting! One of the Specify devs had run in on the Specify code and so thought I would also give it a whirl, but agree some of the suggestions seem a little nonsensical. Did not know about the reputation of W3! Good to know!
